### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by marshalsoft** [jogboms/nativescript-paystack#16]
I'm having this error after installing nativescript-paystack in my project
Running full build
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

**FAILURE: Build failed with an exception.**

* What went wrong:
Execution failed for task ':app:transformClassesWithJarMergingForF0F1F2F3F4F5F6F7F8F9F10F11F12F13F14F15F16Debug'.
> com.android.build.api.transform.TransformException: java.util.zip.ZipException: duplicate entry: okio/AsyncTimeout$1.class

**## package.json**
{
  "description": "myapp",
  "license": "README.md",
  "readme": "Marshalsoft Application",
  "repository": "<fill-your-repository-here>",
  "nativescript": {
    "id": "com.appid.myapp",
    "tns-android": {
      "version": "3.4.1"
    }
  },
  "dependencies": {
    "nativescript-audio": "^3.4.3",
    "nativescript-background-http": "^3.0.0",
    "nativescript-barcodescanner": "^2.7.4",
    "nativescript-camera": "^3.2.1",
    "nativescript-carousel": "^3.1.0",
    "nativescript-email": "^1.4.1",
    "nativescript-floatingactionbutton": "^3.0.0",
    "nativescript-geolocation": "^3.0.0",
    "nativescript-gif": "^2.0.0",
    "nativescript-imagepicker": "^4.0.1",
    "nativescript-insomnia": "^1.2.1",
    "nativescript-keyboardshowing": "^1.0.0",
    "nativescript-local-notifications": "^1.2.1",
    "nativescript-modal-datetimepicker": "^1.0.3",
    "nativescript-okhttp": "0.0.8",
    "nativescript-paystack": "^0.2.1",
    "nativescript-permissions": "^1.2.3",
    "nativescript-phone": "^1.3.1",
    "nativescript-pro-ui": "^3.4.1",
    "nativescript-pulltorefresh": "^2.0.2",
    "nativescript-screen-orientation": "^2.0.0",
    "nativescript-sms-inbox": "^1.0.7",
    "nativescript-social-share": "^1.3.2",
    "nativescript-sqlite": "^1.1.7",
    "nativescript-status-bar": "^1.1.1",
    "nativescript-telephony": "^1.0.4",
    "nativescript-texttospeech": "^1.3.2",
    "nativescript-theme-core": "~1.0.2",
    "nativescript-toolbox": "^3.0.1",
    "nativescript-ui-sidedrawer": "^3.5.0",
    "nativescript-videoplayer": "^3.0.8",
    "nativescript-xml2js": "^0.5.2",
    "nativescript-xmlobjects": "^1.1.4",
    "nativescript-zxing": "^1.5.3",
    "tns-core-modules": "^3.4.1",
    "tns-core-modules-snapshot": "3.0.1-5.5.372.32"
  },
  "devDependencies": {
    "babel-traverse": "6.4.5",
    "babel-types": "6.4.5",
    "babylon": "6.4.5",
    "jasmine-core": "^2.8.0",
    "karma": "^1.7.1",
    "karma-jasmine": "^1.1.0",
    "karma-nativescript-launcher": "^0.4.0",
    "lazy": "1.0.11",
    "nativescript-dev-android-snapshot": "0.0.10",
    "nativescript-dev-typescript": "~0.4.0",
    "tns-platform-declarations": "^3.1.1",
    "typescript": "~2.2.1"
  }
}

**Comment by marshalsoft** [comment]
i have resolve this issue with
## goto app.gradle and include the following lines
configurations{
        all*.exclude module: 'okhttp'
        all*.exclude module: 'okio'
    }

**Comment by jogboms** [comment]
First of @marshalsoft, Sorry for the delayed response.
Its good to know you have resolved the issue all by yourself, but permit me to ask if this issue was developed after the installation of the plugin.
It's as though it introduced conflicts with already existing packages.

**Comment by jogboms** [comment]
closed due to inactivity.
